### PR TITLE
Add uwsgitop to overrides

### PR DESCRIPTION
**Pull request by albertyw**

### CODE REVIEW

**Comment by brettcannon** [comment]
Since that PR has not been accepted yet I'm going to hold off on merging this PR. Once that upstream PR gets merged, update this PR to point to the setup.py file and ping this PR.

**Comment by brettcannon** [comment]
@albertyw Because I keep thinking there's a new PR that I've missed, I'm closing this for now. Feel free to ping or re-open it once the requisite upstream PRs have been merged.

**Comment by albertyw** [comment]
https://github.com/xrmx/uwsgitop/pull/46 is now merged and I've updated the PR to point to https://github.com/xrmx/uwsgitop/blob/master/setup.py#L21

**Comment by brettcannon** [comment]
GitHub is saying I can't re-open the PR because there was a force push or the original branch was recreated. Can you just open a new PR?

**Pull request closed without merging**
