### PR TITLE
Travis CI: Add Python 3.7 production release and 3.8-dev

### PR DESCRIPTION
**Pull request by cclauss**
travis-ci/travis-ci#9069

### CODE REVIEW

**Comment by brettcannon** [comment]
I don't think this change is necessary. The [Travis docs](https://docs.travis-ci.com/user/languages/python/#specifying-python-versions) don't suggest it's needed and I'm already running against Python 3.7 successfully without it. So while I appreciate the PR, I'm not going to accept it. (I'm also purposefully running against `3.6-dev` to know early if something needs to be fixed in either this project or Python itself.)

Now if you  wanted to submit a PR to test against `nightly` and made it optional then I would happily accept that change.

**Comment by cclauss** [comment]
Understood.  Thanks for your review.

Just for the record, the Python 3.7 without these changes is [3.7.0a4+](https://travis-ci.org/brettcannon/caniusepython3/jobs/415656489#L445) which predates the 3.7.0 production release and also the __async__ is a reserved word change.  Similar things with 3.8-dev.  This is documented in the Travis issue.

**Comment by brettcannon** [comment]
Ugh, I wish their docs would say that. 😝 

Then can you put it back to `3.6-dev` and then I will merge the PR.

**Comment by cclauss** [comment]
A notice is in the Travis docs https://docs.travis-ci.com/user/languages/python/#development-releases-support

**Pull request merged**
