### PR TITLE
Only use the futures backport on Python 2.7

### PR DESCRIPTION
**Pull request by rouge8**
The `futures` package does not install on Python 3:

```
Collecting futures (from caniusepython3==6.0.0)
  Using cached https://files.pythonhosted.org/packages/4a/f4/418e844d868e34638486732417fb82b05031910059d88b86aaea9c70f699/futures-3.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is meant only for Python 2.
    It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
    For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
    extras_require={':python_version == "2.7"': ['futures']}
```

### CODE REVIEW

**Comment by rouge8** [comment]
Travis would pass (and I delete the last 2 commits) if caniusepython3 dropped Python 3.3 support, since it seems like several libraries used already have

**Comment by brettcannon** [comment]
Dropping Python 3.3 is totally fine! Would  you rather submit a PR for that, @rouge8 ?

**Comment by rouge8** [comment]
PR to drop 3.3: https://github.com/brettcannon/caniusepython3/pull/179

**Comment by brettcannon** [comment]
Thanks! I'll try to do a release today or tomorrow.

**Pull request merged**
