### PR TITLE
Add tox.ini for tox

### PR DESCRIPTION
**Pull request by msabramo**
```
$ pip install tox
...
$ tox
...
  py26: commands succeeded
  py27: commands succeeded
  py32: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  pypy: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by brettcannon** [comment]
First of, thanks for the PR. I do want to accept this, but I'm wondering if we can clean some stuff up in the process.

Will tox run pip such that it installs what is specified in tests_require in setup.py? If so then could you actually move what is in dev_requirements.txt directly into setup.py and delete dev_requirements.txt?

**Comment by brettcannon** [comment]
Actually, the other question is how this will affect Travis (if at all), including whether it affects dropping dev_requirements.txt.

**Comment by msabramo** [comment]
> Will tox run pip such that it installs what is specified in tests_require in setup.py? If so then could you actually move what is in dev_requirements.txt directly into setup.py and delete dev_requirements.txt?

I believe so. Let me try it, so we know for sure.

> Actually, the other question is how this will affect Travis (if at all), including whether it affects dropping dev_requirements.txt.

Actually what I normally do is rewrite the `.travis.yml` to use a trick that makes it reuse `tox` which makes everything more DRY. I didn't do that here, because I was trying to make the PR small and less controversial.

The basic idea is this: https://github.com/SurveyMonkey/pyteamcity/blob/master/.travis.yml -- basically it installs tox and then sets this `TOXENV` variable appropriately and everything works very nicely.

I can update this PR to use that trick if you like it.

**Comment by msabramo** [comment]
>> Will tox run pip such that it installs what is specified in tests_require in setup.py? If so then could you actually move what is in dev_requirements.txt directly into setup.py and delete dev_requirements.txt?

> I believe so. Let me try it, so we know for sure.

Or not :smile: 

https://bitbucket.org/hpk42/tox/issue/13/tox-should-reuse-tests_require

**Comment by msabramo** [comment]
See https://github.com/msabramo/caniusepython3/commit/362ed2017315023b57ad78ca6fa5744650e81aba for the `.travis.yml` change to make it more DRY.

**Comment by brettcannon** [comment]
We will give this a try and see what happens! =)

**Pull request merged**
