### PR TITLE
Added futures

### PR DESCRIPTION
**Pull request by Dundee**
Futures are backport of concurrent.futures from python 3.

### CODE REVIEW

**Comment by brettcannon** [comment]
Can you change the reference link to point to the docs for concurrent.futures?

**Comment by Dundee** [comment]
Changed.

**Comment by brettcannon** [comment]
Change that link to point to the latest 3 docs -- just replace "3.4" with "3" in the URL -- and I will happily accept the PR.

**Comment by Dundee** [comment]
Ok, thanks :)

**Comment by brettcannon** [comment]
Thanks!

**Pull request merged**
