### PR TITLE
Added django-robots to overrides.json

### PR DESCRIPTION
**Pull request by tspecht**
Adds django-robots (https://pypi.python.org/pypi/django-robots) to overrides.json.

### CODE REVIEW

**Comment by brettcannon** [comment]
I didn't see any mention of Python 3 support on the PyPI page nor anything on the GitHub page. Is there any documentation showing that the current release supports Python 3?

**Comment by brettcannon** [comment]
Maybe @jezdez can tell us if django-robots is Python 3 compatible in its current release or will be (and add the trove classifier :smile: ).

**Comment by jezdez** [comment]
Heh! Python 3 is not supported at the moment, hence the lack of a Trove classifier for it.

It's an old package and just hasn't been worked on much in past years. That said, it's now hosted by [Jazzband](https://jazzband.co/) so you can join yourself. [More info](https://jazzband.co/news/2015/12/17/launching-jazzband).

**Comment by brettcannon** [comment]
Since there is no Python 3 support I'm closing this PR.

**Pull request closed without merging**
