### PR TITLE
Add override for flask-login

### PR DESCRIPTION
**Pull request by dhamaniasad**

### CODE REVIEW

**Comment by brettcannon** [comment]
Does this apply to version 0.3.0? If so then this doesn't apply yet since version 0.3.0 is not on PyPI yet.

PS: please alphabetize the project names I'm the file I'm the future.

**Comment by dhamaniasad** [comment]
The current release (0.2.11) does [seem to support Python 3](https://github.com/maxcountryman/flask-login/blob/528e1efc69162b433825c4c02f62a1226eadc570/.travis.yml).

**Comment by brettcannon** [comment]
If you can update the justification to the link you provided earlier I will accept the PR.

**Comment by dhamaniasad** [comment]
Done.

**Comment by brettcannon** [comment]
Thanks!

**Pull request merged**
